databases:
  - name: marjane-db
    plan: free
    databaseName: marjane_db

services:
  - type: web
    name: marjane-api
    plan: free
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: marjane-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

  - type: web
    name: marjane-chatbot
    plan: free
    runtime: python
    rootDir: chatbot
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.10"
      - key: MARJANE_API_URL
        value: https://marjane-security.onrender.com
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
